import { Item } from "../app/context/types"

export const data: Item[] = [{
  id: "1001",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "female",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://fastly.picsum.photos/id/0/5000/3333.jpg?hmac=_j6ghY5fCfSD6tvtcV74zXivkJSPIfR9B8w34XeQmvU",
  status: "online",
  credits: 30,
  tags: "Highly available",
},
{
  id: "1002",
  firstName: "Ben",
  lastName: "Moore",
  age: 29,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://fastly.picsum.photos/id/16/2500/1667.jpg?hmac=uAkZwYc5phCRNFTrV_prJ_0rP0EdwJaZ4ctje2bY7aE",
  status: "offline",
  credits: 30
},
{
  id: "1003",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 35,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://www.gstatic.com/webp/gallery/2.webp",
  status: "online",
  credits: 30
},
{
  id: "1004",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 46,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://www.gstatic.com/webp/gallery/5.jpg",
  status: "online",
  credits: 30
},
{
  id: "1005",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 55,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://www.gstatic.com/webp/gallery/4.webp",
  status: "online",
  credits: 30
},
{
  id: "1006",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 42,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://file-examples.com/storage/fe1b07b09f67bcb9b96354c/2020/03/file_example_WEBP_50kB.webp",
  status: "online",
  credits: 30
},
{
  id: "1007",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 18,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://www.gstatic.com/webp/gallery/1.sm.webp",
  status: "online",
  credits: 30
},
{
  id: "1008",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 20,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://www.gstatic.com/webp/gallery/1.sm.jpg",
  status: "online",
  credits: 30
},
{
  id: "1009",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 34,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1010",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 25,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1011",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 32,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1012",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 37,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://www.gstatic.com/webp/gallery/2.webp",
  status: "online",
  credits: 30
},
{
  id: "1013",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 29,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1014",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 65,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://www.gstatic.com/webp/gallery/2.webp",
  status: "online",
  credits: 30
}, {
  id: "1015",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 23,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1016",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1017",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1018",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1019",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1020",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1021",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1022",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1023",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1024",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1025",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 26,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1026",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1027",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1028",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1029",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1030",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
{
  id: "1031",
  firstName: "Amanda",
  lastName: "Cerni",
  age: 30,
  region: "USA",
  gender: "FEMALE",
  languages: ["American", "English"],
  bookmarked: false,
  flagUrl: "asdasdas",
  profileImage: "https://flirtbate.com/images/valentine/Pre-signup-valentine.webp",
  status: "online",
  credits: 30
},
]

